spring.application.name=E-Commerce
# Activating a local profile to use DB URL, Username, Password & Driver property
spring.profiles.active=local

# ====================
# Database
# ====================

# DB (connection URL, username, password, driver class)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_Username}
spring.datasource.password=${DB_Password}
spring.datasource.driver-class-name=${DB_Driver}

# ====================
# JPA / Hibernate
# ====================

# Use PostgreSQL SQL rules (often auto-detected)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (Update tables, Print SQL, Format SQL to read easily)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.prefix=/api/v1